// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmgmLTmdov7sKRrKUGquRA6QEp-yxbSVo',
    appId: '1:916265304547:web:9303caeb64a3ff0cfba0d6',
    messagingSenderId: '916265304547',
    projectId: 'senior-health-care',
    authDomain: 'senior-health-care.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'APIKEY-to4aY',
    appId: '1:916265304547:android:9303caeb64a3ff0cfba0d6',
    messagingSenderId: '916265304547',
    projectId: 'senior-health-care',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'APIKEY',
    appId: '1:916265304547:ios:9303caeb64a3ff0cfba0d6',
    messagingSenderId: '916265304547',
    projectId: 'senior-health-care',
    iosClientId:
        '916265304547-ha0kik5b05gse7o07cfbp71vas5t7v6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.senior-health-care',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'APIKEY',
    appId: '1:916265304547:ios:9303caeb64a3ff0cfba0d6',
    messagingSenderId: '916265304547',
    projectId: 'senior-health-care',
    iosClientId:
        '916265304547-ha0kik5b05gse7o07cfbp71vas5t7v6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.senior-health-care',
  );
}
